name: build
on: [ push, pull_request ]
jobs:
  applications:
    name: application test suite
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - name: 构建
        run: |
          chmod +x mvnw
          ./mvnw -ntp -Pgithub clean package -DskipTests -e -U
#            - name: 校验
#              run: ./mvnw -ntp -Pgithub verify
